# Makefile for hello, test program for the test harness of the ABC Tool Box.

# The test program is made from a single file.
hello: hello.cpp
	g++ hello.cpp -L/usr/local/include/ABC -lhello-world -o hello
