#! /bin/bash
# Creates a link to the currant directory for easy access.

# Print the usage.
function usage ()
{
  echo "Usage: $0 ([directory]| -h)"
}

# Create a link from the directory in $1 to the include directory.
function makelink ()
{
  # Save the location of the target directory.
  TARGET=$1
  
  # Get the directory of the ABCtoolbox, i.e. the one that contains this file.
  HEREPATH="$(cd "$(dirname "$0" )" && pwd)"
  # Create a path to the include directory (containing .hpp and .o files).
  INCLUDE=$HEREPATH/include
  
  # Create the link.
  ln --symbolic -t $TARGET $INCLUDE
}

# Show the help information for the script
function showhelp ()
{
  usage
  echo 
}

echo "Still in beta"

# Check for good input.
if [ $# -gt 2 ]; then
  usage
  exit 1

# No peramiter: Standard usage:
elif [ "$1" ==  ""  ]; then
  makelink /usr/bin/include_ # Check that before testing. !!!!! !!!!!

# -h option: Help usage:
elif [ "$1" == "-h" ]; then
  showhelp

# Check for a proper directory.
elif [ ! -d $1 ]; then
  echo $1 is not a directory.
  exit 2

# Create a link in the directory.
else
  makelink $1
fi

### Alt:

# Creates a link from a directory searched by the g++ -l flag (/usr/include ?)
# to where the objects/headers for ABC Tool Box are.
