# Make file for the ABC Tool Box:
# Not currantly working, WIP

# See DevManual.txt for details.

# The names of all of the tools.
TOOLLIST= hello-world



# Compiler Varaibles:
CXX=gcc
CXXFLAGS=-Wall -MMD -std=c++11

# Is it possible to link in libraries ahead of time,
# As well as join the partally made objects together?
LINK=ld
LINKFLAGS=-Ur

# Directory names:
# Code/Source Directory, holds raw files not created by make.
SORDIR=code
# Object/Intermediate Directory, files both generated and used by make
#   which are mostly objects.
OBJDIR=obj
# Library/Target Directory, holds the end results of make.
LIBDIR=include



# Special Rules:
.PHONY : all clean $(TOOLLIST)
.SECONDEXPANSION :

# Misc Varibles:
ALLCPP= $(wildcard $(SORDIR)/*/*.cpp)
INTOBJ= $(patsubst $(SORDIR)%.cpp,$(OBJDIR)%.o,$(ALLOBJ))
FINOBJ= $(patsubst %,$(OBJDIR)/%.o,$(TOOLLIST))
DEPEND= $(INTOBJ:.o=.d)

# Functions:
# Turns the names of tools it is given to the names of the tool's final
#   files, toollib is the library file, toolhead is the public header and
#   end files produces both.
endfiles= $(foreach tool,$(1),$(LIBDIR)/$(tool).hpp $(LIBDIR)/lib$(tool).a)
toollib = $(foreach tool,$(1),$(LIBDIR)/lib$(tool).a)
toolhead= $(foreach tool,$(1),$(LIBDIR)/$(tool).hpp)
# Expands to the contents of the file $(1) if file exists.
#   If the file does not exist expands to the empty string.
safecat= $(shell [ -e $(1) ] && cat $(1))



### Rules:

# Default rule, updates all tools.
all : $(TOOLLIST)

# Tool level rule, create all final files for a tool.
$(TOOLLIST) : $(LIBDIR)/$$@.hpp $(LIBDIR)/lib$$@.a

# Create the static library in the include directory.
$(LIBDIR)/lib%.a : $(OBJDIR)/%.o | $(LIBDIR)
	ar rcs $@ $<

# Copy the public header over to the include directory.
#$(call toolhead,$(TOOLLIST)) :
$(LIBDIR)/%.hpp : $(SORDIR)/%/$$*.hpp | $(LIBDIR)
	cp $< $@

# Rule for final objects (objects generated by linking)
$(FINOBJ) : $(OBJDIR)/%.o : $$(filter $(OBJDIR)/$$*/%.o,$(INTOBJ)) | $(OBJDIR)
	$(LINK) $(LINKFLAGS) $^ $(call safecat, $(SORDIR)/$*/libs) -o $@

# Rule for intermediate objects (objects created from code)
$(INTOBJ) : $(OBJDIR)/%.o : $(SORDIR)/%.cpp | $(OBJDIR)/$$(dir $$*)
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Directory creation.
$(OBJDIR) $(LIBDIR) :     ; mkdir $@
$(OBJDIR)/% : | $(OBJDIR) ; mkdir $@



# Add dependancy files.
-include $(DEPEND)

# clean phony rule. Remove all intermetiate files.
clean :
	-rm $(OBJDIR)/*/*.o
	-rm $(OBJDIR)/*/*.d
	-rmdir $(OBJDIR)/*
	-rmdir $(OBJDIR)

# I think it is eval that creates new makefile contents.
# $(foreach tool,$(TOOLLIST), \
#   $(eval $(tool)_INT=\
#     $(filter $(OBJDIR)/$(tool)/%.o,$(INTOBJ))))
# Creates a *_INT varible for each tool that contains the names of all
# intermediate objects used to create that tool.
